### PR TITLE
feat(config): Add convict config

### LINKED ISSUE #100: use env vars for all config options
either use convict, or use process.ENV and document the vars in the readme

### PR DESCRIPTION
**Pull request by pdehaan**
Fixes #100

### CODE REVIEW

**Comment by mostlygeek** [comment]
the `aws.config` part and usage looks good to me. In prod these values are pulled out of the EC2 metadata via the IAM roles. The aws-sdk will do this automatically as long as `aws.config` as undefined for things.

**Comment by 6a68** [comment]
Whoops, missed this one yesterday. Looks great, testing locally now.

**Comment by 6a68** [comment]
Bring on the convict!



Thanks @pdehaan!

**Pull request merged**
