### PR TITLE
Relicense to Apache 2 & give proper attribution.

### LINKED ISSUE #34: Fixup license, notice, and code blocks
License: the Amazon portions are Apache 2 licensed. I don't know how we mix that with MPL2. I'm fine with this repo being Apache 2 licensed, idk.

Notice: As long as we have a NOTICE file that includes the contents of the original repo's NOTICE file, I think we are fine to remove the existing copyright-related code block from server.js, based on http://www.apache.org/dev/apply-license.html#copy-per-file.

Code blocks: I think @pdehaan has some magic little thing that shoves the MPL code block into the top of files. We could do that, it'd be nice, but not necessary.

### PR DESCRIPTION
**Pull request by 6a68**
- Since this code is derived from an Apache 2.0 licensed work, this
    code should be published under the same license.
  - As a courtesy, added the original authors to the AUTHORS file, since
    the point of that file is to give attribution to all contributors.
  - Added a NOTICE file, including the contents of the NOTICE file
    included in the repo from which our work is derived, along with a
    link to that repo.

  Fixes #34.

### CODE REVIEW

**Comment by 6a68** [comment]
Legal stuff is fun :tada: :balloon: :balloon: 

@lmorchard, mind reviewing? I haven't done this in a while, but I think I'm covering all the requirements set by Mozilla legal and the terms of the Apache 2 license. There are some links to relevant Mozilla pages in the parent bug, #34.

**Comment by meandavejustice** [comment]
Linter failed now that we don't use the `gulp-committers` lib in out gulpfile. We should also remove the dep from `package.json`

**Comment by meandavejustice** [comment]
Also thanks for taking care of this.

**Comment by 6a68** [comment]
Aha, right. Thanks @meandavejustice!

**Comment by 6a68** [comment]
just going to land this and clear the queue

**Pull request merged**
